### ISSUE TITLE
日服运行报错

### ISSUE THREAD

**Issue by SmartCooker** [U-rara/lol-loot-repeated-redemption#3]
运行exe后生成一txt文件
{'errorCode': 'RPC_ERROR', 'httpStatus': 500, 'implementationDetails': {}, 'message': 'Unexpected status in ProcessPlayerLootUpdateResponse: CLIENT_ERROR'}

**Comment by U-rara** [comment]
确认代币数量>2200嘛

**Comment by SmartCooker** [comment]
是我的问题，2200代币可以换了
